ARG REGISTRY=''
ARG BASE_TAG=''
FROM ${REGISTRY}pyprt-base:${BASE_TAG}

ARG PY_VER
ARG PY_VER_MICRO

# dependencies for Python source build (also used for module native extensions)
RUN yum -y update \
    && yum install -y gcc gcc-c++ make openssl11 openssl11-libs \
      openssl11-static openssl11-devel libffi-devel bzip2-devel liblzma-dev \
    && yum clean all \
    && rm -rf /var/cache/yum

# we manually build Python with default CentOS 7 toolchain
ADD https://www.python.org/ftp/python/${PY_VER}${PY_VER_MICRO}/Python-${PY_VER}${PY_VER_MICRO}.tar.xz /tmp/python_src.tar.xz
RUN tar xf /tmp/python_src.tar.xz -C /tmp \
    && rm /tmp/python_src.tar.xz \
    && pushd /tmp/Python-${PY_VER}${PY_VER_MICRO} \
    && sed -i 's/PKG_CONFIG openssl /PKG_CONFIG openssl11 /g' configure \
    && ./configure \
    && CPU_COUNT=$(grep -c ^processor /proc/cpuinfo) \
    && make -j$CPU_COUNT altinstall \
    && popd \
    && rm -rf /tmp/Python-${PY_VER}${PY_VER_MICRO}

## also see https://github.com/sclorg/devtoolset-container
RUN echo "unset BASH_ENV PROMPT_COMMAND ENV && source scl_source enable devtoolset-9" >> /tmp/scl_enable
ENV BASH_ENV=/tmp/scl_enable ENV=/tmp/scl_enable PROMPT_COMMAND=". /tmp/scl_enable"

COPY envs/linux/wheel/requirements-py${PY_VER}.txt /tmp/pyprt/requirements.txt

ENV VIRTUAL_ENV=/tmp/pyprt/venv
RUN python${PY_VER} -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python -V \
    && python -m pip install --no-cache-dir --upgrade pip  \
    && python -m pip install --no-cache-dir --upgrade wheel \
    && python -m pip install --no-cache-dir -r requirements.txt \
    && rm /tmp/pyprt/requirements.txt
