ARG REGISTRY=''
ARG BASE_TAG=''
FROM ${REGISTRY}pyprt-base:${BASE_TAG}

ARG PY_VER
ARG PY_VER_MICRO

# dependencies for Python source build (also used for module native extensions)
RUN set -e \
    && dnf -y update \
    && INSTALL_PKGS="libffi-devel bzip2-devel xz-devel krb5-devel openssl openssl-libs openssl-devel" \
    && dnf install -y --setopt=tsflags=nodocs $INSTALL_PKGS \
    && rpm -V $INSTALL_PKGS \
    && dnf clean all && rm -rf /var/cache/dnf

# we manually build Python with default toolchain
ADD https://www.python.org/ftp/python/${PY_VER}${PY_VER_MICRO}/Python-${PY_VER}${PY_VER_MICRO}.tar.xz /tmp/python_src.tar.xz
RUN tar xf /tmp/python_src.tar.xz -C /tmp \
    && rm /tmp/python_src.tar.xz \
    && pushd /tmp/Python-${PY_VER}${PY_VER_MICRO} \
    && ./configure \
    && CPU_COUNT=$(grep -c ^processor /proc/cpuinfo) \
    && make -j$CPU_COUNT altinstall \
    && popd \
    && rm -rf /tmp/Python-${PY_VER}${PY_VER_MICRO}

## also see https://github.com/sclorg/devtoolset-container
RUN echo "unset BASH_ENV PROMPT_COMMAND ENV && source scl_source enable gcc-toolset-11" >> /tmp/scl_enable
ENV BASH_ENV=/tmp/scl_enable ENV=/tmp/scl_enable PROMPT_COMMAND=". /tmp/scl_enable"

COPY envs/linux/wheel/requirements-py${PY_VER}.txt /tmp/pyprt/requirements.txt

ENV VIRTUAL_ENV=/tmp/pyprt/venv
RUN python${PY_VER} -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python -V \
    && python -m pip install --no-cache-dir --upgrade pip  \
    && python -m pip install --no-cache-dir --upgrade wheel \
    && python -m pip install --no-cache-dir -r requirements.txt \
    && rm /tmp/pyprt/requirements.txt
